investigated parallel deploy and undeploy.
FOUnd errros wih parallel depoy due to RDK using gettempdir.
gettempdir is such that (on my mac) all parallel processes
get the same directory Changed the rdk pacakes  to to  use
tempfile.mkdtemp whcih make a directory unique to each process.

With gettempdir, deply had errrors, undeploy did not.
wiht mkdtemp, have yet to observe errors with deploy
and undeploy.

Left a hook in rdk_manage that enabels one to choose
parallelism of 1 incase future problems emerge.

an observed dettemodr error was
FileNotFoundError: [Errno 2] No such file or directory: ‘/var/folders/_c/m03r173s5ms6947lcj1ygqrc0000gp/T/scimma_resources_have_required_tags.zip’
Eviednely on process cleanin up the common directory
in a race condition.